create only structure of leaderboard
huzaifakhan0308/Leader-board pull request #1
Opened 2023-01-31 22:33 UTC by huzaifakhan0308

- set up the project with webpack.
- create a structure for the leaderboard.
- add modules

2023-01-31 23:15 UTC, Owusu-Desmond requested changes
Hi @huzaifakhan0308 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] **NOTE** :warning:  Please next time make sure that the branch should have the name of a feature or action (e.g. `created_sidebar` or `added_comments_section`, `created_form` or `created_form_section`). But for now, as you can see you have your branch `leaderboard-project1` which does not match what you worked on in this branch :smile: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 23:15 UTC, Owusu-Desmond commented on README.md
> +
- [ ] Please make sure that you have a list of at least 3 key feature that was implemented in this project :pray:

2023-01-31 23:15 UTC, Owusu-Desmond commented on README.md
> +- [Live Demo Link]()
- [ ] Since you have no live demo link yet, please make sure that you remove this broken link. You can write here `LIVE DEMO UNAVAILABLE`

2023-02-01 11:06 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @huzaifakhan0308, 

To highlight 👍🏽 
✔️ App is setup correctly

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/749155b89333c6d89386f5c98dd110e234a00f2aa1e864a5b3fecaf089aedb27/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f36664a31424d375232454252446e784b2f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-02-01 17:35 UTC, merged